<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.opentmf</groupId>
  <artifactId>opentmf-versions</artifactId>
  <version>1.3.2-SNAPSHOT</version>
  <packaging>pom</packaging>

  <description>
    A Super pom project that exposes the latest release versions of opentmf-commons artifacts.
  </description>

  <url>https://github.com/opentmf/opentmf-versions</url>

  <organization>
    <name>PiA Group</name>
    <url>https://www.pia-group.net/</url>
  </organization>

  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
      <comments>A permissive open-source license</comments>
    </license>
  </licenses>

  <developers>
    <developer>
      <id>gokhanus</id>
      <name>Gokhan Demir</name>
      <email>gokhan@opentmf.org</email>
    </developer>
    <developer>
      <id>yusuf-bozkurt</id>
      <name>Yusuf Bozkurt</name>
      <email>yusuf.bozkurt@pia-team.com</email>
    </developer>
    <developer>
      <id>cezmi-aslan</id>
      <name>Cezmi Aslan</name>
      <email>cezmi.aslan@pia-team.com</email>
    </developer>
    <developer>
      <id>abdullahbeker</id>
      <name>Abdullah Beker</name>
      <email>abdullah.beker@dnext-technology.com</email>
    </developer>
    <developer>
      <id>sezer</id>
      <name>Sezer Aydin</name>
      <email>sezer.aydin@pia-team.com</email>
    </developer>
  </developers>

  <properties>
    <openid-rbac-security.version>1.1.0</openid-rbac-security.version>
    <opentmf-commons.version>1.0.5</opentmf-commons.version>
    <opentmf-db-lock-service.version>1.0.8</opentmf-db-lock-service.version>
    <camunda7-bpmn-sync-service.version>1.1.1</camunda7-bpmn-sync-service.version>
    <dnext-catalog-sync-service.version>1.1.0</dnext-catalog-sync-service.version>
    <auditor-aware-jpa.version>1.0.3</auditor-aware-jpa.version>

    <camunda7-incident-logger.version>1.0.3</camunda7-incident-logger.version>
    <opentmf-mockserver.version>1.0.2</opentmf-mockserver.version>
    <camunda7-test-framework.version>1.0.4</camunda7-test-framework.version>
    <opentmf-camunda7.version>23.0.0</opentmf-camunda7.version>

    <opentmf-v4-models.version>1.0.5</opentmf-v4-models.version>
    <opentmf-620-v4-model.version>4.1.0.5</opentmf-620-v4-model.version>
    <opentmf-622-v4-model.version>4.0.0.5</opentmf-622-v4-model.version>
    <opentmf-629-v4-model.version>4.0.0.5</opentmf-629-v4-model.version>
    <opentmf-632-v4-model.version>4.0.0.5</opentmf-632-v4-model.version>
    <opentmf-633-v4-model.version>4.0.0.5</opentmf-633-v4-model.version>
    <opentmf-634-v4-model.version>4.1.0.5</opentmf-634-v4-model.version>
    <opentmf-637-v4-model.version>4.0.0.5</opentmf-637-v4-model.version>
    <opentmf-638-v4-model.version>4.0.0.5</opentmf-638-v4-model.version>
    <opentmf-639-v4-model.version>4.0.0.5</opentmf-639-v4-model.version>
    <opentmf-641-v4-model.version>4.1.0.5</opentmf-641-v4-model.version>
    <opentmf-648-v4-model.version>4.0.0.5</opentmf-648-v4-model.version>
    <opentmf-651-v4-model.version>4.0.0.5</opentmf-651-v4-model.version>
    <opentmf-652-v4-model.version>4.0.0.5</opentmf-652-v4-model.version>
    <opentmf-663-v4-model.version>4.0.0.5</opentmf-663-v4-model.version>
    <opentmf-666-v4-model.version>4.0.0.5</opentmf-666-v4-model.version>
    <opentmf-669-v4-model.version>4.0.0.5</opentmf-669-v4-model.version>
    <opentmf-673-v4-model.version>4.0.1.5</opentmf-673-v4-model.version>
    <opentmf-674-v4-model.version>4.0.0.5</opentmf-674-v4-model.version>
    <opentmf-675-v4-model.version>4.0.0.5</opentmf-675-v4-model.version>
    <opentmf-681-v4-model.version>4.0.0.5</opentmf-681-v4-model.version>
    <opentmf-customer-v4-model.version>4.0.0.5</opentmf-customer-v4-model.version>
    <opentmf-resource-v4-model.version>4.1.0.5</opentmf-resource-v4-model.version>
    <opentmf-service-v4-model.version>4.1.0.5</opentmf-service-v4-model.version>
    <opentmf-product-v4-model.version>4.1.0.5</opentmf-product-v4-model.version>
    <opentmf-common-v4-model.version>4.1.0.5</opentmf-common-v4-model.version>

    <dnext-opentmf-v4-models.version>1.1.0</dnext-opentmf-v4-models.version>
    <dnext-opentmf-620-v4-model.version>4.0.0.10</dnext-opentmf-620-v4-model.version>
    <dnext-opentmf-622-v4-model.version>4.0.0.10</dnext-opentmf-622-v4-model.version>
    <dnext-opentmf-633-v4-model.version>4.0.0.10</dnext-opentmf-633-v4-model.version>
    <dnext-opentmf-638-v4-model.version>4.0.0.10</dnext-opentmf-638-v4-model.version>
    <dnext-opentmf-641-v4-model.version>4.1.0.10</dnext-opentmf-641-v4-model.version>
    <dnext-opentmf-663-v4-model.version>4.1.0.10</dnext-opentmf-663-v4-model.version>
    <dnext-opentmf-666-v4-model.version>4.0.0.10</dnext-opentmf-666-v4-model.version>
    <dnext-opentmf-common-v4-model.version>4.1.0.10</dnext-opentmf-common-v4-model.version>

    <opentmf-v4-utils.version>1.0.5</opentmf-v4-utils.version>
    <opentmf-622-v4-util.version>1.0.5</opentmf-622-v4-util.version>
    <opentmf-641-v4-util.version>1.0.5</opentmf-641-v4-util.version>
    <opentmf-common-v4-util.version>1.0.5</opentmf-common-v4-util.version>

    <opentmf-web-clients.version>1.1.1</opentmf-web-clients.version>
    <opentmf-webclients-common.version>1.1.1</opentmf-webclients-common.version>
    <opentmf-openid-webclient-provider.version>1.1.1</opentmf-openid-webclient-provider.version>
    <opentmf-openid-webclients-starter.version>1.1.1</opentmf-openid-webclients-starter.version>
    <opentmf-basic-webclient-provider.version>1.1.1</opentmf-basic-webclient-provider.version>
    <opentmf-basic-webclients-starter.version>1.1.1</opentmf-basic-webclients-starter.version>
    <test-all-clients.version>1.1.1</test-all-clients.version>

    <opentmf-clients-base.version>1.1.1</opentmf-clients-base.version>

    <opentmf-v4-clients.version>1.1.2</opentmf-v4-clients.version>
    <opentmf-620-v4-client.version>1.1.2</opentmf-620-v4-client.version>
    <opentmf-622-v4-client.version>1.1.2</opentmf-622-v4-client.version>
    <opentmf-629-v4-client.version>1.1.2</opentmf-629-v4-client.version>
    <opentmf-632-v4-client.version>1.1.2</opentmf-632-v4-client.version>
    <opentmf-633-v4-client.version>1.1.2</opentmf-633-v4-client.version>
    <opentmf-634-v4-client.version>1.1.2</opentmf-634-v4-client.version>
    <opentmf-637-v4-client.version>1.1.2</opentmf-637-v4-client.version>
    <opentmf-638-v4-client.version>1.1.2</opentmf-638-v4-client.version>
    <opentmf-639-v4-client.version>1.1.2</opentmf-639-v4-client.version>
    <opentmf-641-v4-client.version>1.1.2</opentmf-641-v4-client.version>
    <opentmf-648-v4-client.version>1.1.2</opentmf-648-v4-client.version>
    <opentmf-652-v4-client.version>1.1.2</opentmf-652-v4-client.version>
    <opentmf-663-v4-client.version>1.1.2</opentmf-663-v4-client.version>
    <opentmf-666-v4-client.version>1.1.2</opentmf-666-v4-client.version>
    <opentmf-669-v4-client.version>1.1.2</opentmf-669-v4-client.version>
    <opentmf-681-v4-client.version>1.1.2</opentmf-681-v4-client.version>
    <opentmf-hub-v4-client.version>1.1.2</opentmf-hub-v4-client.version>

    <!-- Plugins related to release and deployment -->
    <maven-enforcer-plugin.version>3.5.0</maven-enforcer-plugin.version>
    <maven-deploy-plugin.version>3.1.4</maven-deploy-plugin.version>
    <maven-release-plugin.version>3.1.1</maven-release-plugin.version>
    <maven-gpg-plugin.version>3.2.7</maven-gpg-plugin.version>
    <central-publishing-maven-plugin.version>0.7.0</central-publishing-maven-plugin.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.opentmf.security</groupId>
        <artifactId>openid-rbac-security</artifactId>
        <version>${openid-rbac-security.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.commons</groupId>
        <artifactId>opentmf-commons</artifactId>
        <version>${opentmf-commons.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.util</groupId>
        <artifactId>opentmf-db-lock-service</artifactId>
        <version>${opentmf-db-lock-service.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.camunda</groupId>
        <artifactId>camunda7-bpmn-sync-service</artifactId>
        <version>${camunda7-bpmn-sync-service.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.dnext</groupId>
        <artifactId>dnext-catalog-sync-service</artifactId>
        <version>${dnext-catalog-sync-service.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.util</groupId>
        <artifactId>auditor-aware-jpa</artifactId>
        <version>${auditor-aware-jpa.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.camunda</groupId>
        <artifactId>camunda7-incident-logger</artifactId>
        <version>${camunda7-incident-logger.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.mockserver</groupId>
        <artifactId>opentmf-mockserver</artifactId>
        <version>${opentmf-mockserver.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.camunda</groupId>
        <artifactId>camunda7-test-framework</artifactId>
        <version>${camunda7-test-framework.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.camunda</groupId>
        <artifactId>opentmf-camunda7</artifactId>
        <version>${opentmf-camunda7.version}</version>
      </dependency>

      <!-- OpenTMF v4 Models -->
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-v4-models</artifactId>
        <version>${opentmf-v4-models.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-620-v4-model</artifactId>
        <version>${opentmf-620-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-622-v4-model</artifactId>
        <version>${opentmf-622-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-629-v4-model</artifactId>
        <version>${opentmf-629-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-632-v4-model</artifactId>
        <version>${opentmf-632-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-633-v4-model</artifactId>
        <version>${opentmf-633-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-634-v4-model</artifactId>
        <version>${opentmf-634-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-637-v4-model</artifactId>
        <version>${opentmf-637-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-638-v4-model</artifactId>
        <version>${opentmf-638-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-639-v4-model</artifactId>
        <version>${opentmf-639-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-641-v4-model</artifactId>
        <version>${opentmf-641-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-648-v4-model</artifactId>
        <version>${opentmf-648-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-651-v4-model</artifactId>
        <version>${opentmf-651-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-652-v4-model</artifactId>
        <version>${opentmf-652-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-663-v4-model</artifactId>
        <version>${opentmf-663-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-666-v4-model</artifactId>
        <version>${opentmf-666-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-669-v4-model</artifactId>
        <version>${opentmf-669-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-673-v4-model</artifactId>
        <version>${opentmf-673-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-674-v4-model</artifactId>
        <version>${opentmf-674-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-675-v4-model</artifactId>
        <version>${opentmf-675-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-681-v4-model</artifactId>
        <version>${opentmf-681-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-customer-v4-model</artifactId>
        <version>${opentmf-customer-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-resource-v4-model</artifactId>
        <version>${opentmf-resource-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-service-v4-model</artifactId>
        <version>${opentmf-service-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-product-v4-model</artifactId>
        <version>${opentmf-product-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.model</groupId>
        <artifactId>opentmf-common-v4-model</artifactId>
        <version>${opentmf-common-v4-model.version}</version>
      </dependency>

      <!-- DNext TMF v4 Model Extensions -->
      <dependency>
        <groupId>org.opentmf.dnext</groupId>
        <artifactId>dnext-opentmf-v4-models</artifactId>
        <version>${dnext-opentmf-v4-models.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.dnext</groupId>
        <artifactId>dnext-opentmf-620-v4-model</artifactId>
        <version>${dnext-opentmf-620-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.dnext</groupId>
        <artifactId>dnext-opentmf-622-v4-model</artifactId>
        <version>${dnext-opentmf-622-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.dnext</groupId>
        <artifactId>dnext-opentmf-633-v4-model</artifactId>
        <version>${dnext-opentmf-633-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.dnext</groupId>
        <artifactId>dnext-opentmf-638-v4-model</artifactId>
        <version>${dnext-opentmf-638-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.dnext</groupId>
        <artifactId>dnext-opentmf-641-v4-model</artifactId>
        <version>${dnext-opentmf-641-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.dnext</groupId>
        <artifactId>dnext-opentmf-663-v4-model</artifactId>
        <version>${dnext-opentmf-663-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.dnext</groupId>
        <artifactId>dnext-opentmf-666-v4-model</artifactId>
        <version>${dnext-opentmf-666-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.dnext</groupId>
        <artifactId>dnext-opentmf-common-v4-model</artifactId>
        <version>${dnext-opentmf-common-v4-model.version}</version>
      </dependency>

      <!-- OpenTMF v4 Utils -->
      <dependency>
        <groupId>org.opentmf.util</groupId>
        <artifactId>opentmf-v4-utils</artifactId>
        <version>${opentmf-v4-utils.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.util</groupId>
        <artifactId>opentmf-622-v4-util</artifactId>
        <version>${opentmf-622-v4-util.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.util</groupId>
        <artifactId>opentmf-641-v4-util</artifactId>
        <version>${opentmf-641-v4-util.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.util</groupId>
        <artifactId>opentmf-common-v4-util</artifactId>
        <version>${opentmf-common-v4-util.version}</version>
      </dependency>

      <!-- OpenTMF Web Clients -->
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>opentmf-web-clients</artifactId>
        <version>${opentmf-web-clients.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>opentmf-webclients-common</artifactId>
        <version>${opentmf-webclients-common.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>opentmf-openid-webclient-provider</artifactId>
        <version>${opentmf-openid-webclient-provider.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>opentmf-openid-webclients-starter</artifactId>
        <version>${opentmf-openid-webclients-starter.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>opentmf-basic-webclient-provider</artifactId>
        <version>${opentmf-basic-webclient-provider.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>opentmf-basic-webclients-starter</artifactId>
        <version>${opentmf-basic-webclients-starter.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>test-all-clients</artifactId>
        <version>${test-all-clients.version}</version>
      </dependency>

      <!-- OpenTMF Clients Base -->
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>opentmf-clients-base</artifactId>
        <version>${opentmf-clients-base.version}</version>
      </dependency>

      <!-- OpenTMF v4 Clients -->
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>opentmf-v4-clients</artifactId>
        <version>${opentmf-v4-clients.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>opentmf-620-v4-client</artifactId>
        <version>${opentmf-620-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>opentmf-622-v4-client</artifactId>
        <version>${opentmf-622-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>opentmf-629-v4-client</artifactId>
        <version>${opentmf-629-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>opentmf-632-v4-client</artifactId>
        <version>${opentmf-632-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>opentmf-633-v4-client</artifactId>
        <version>${opentmf-633-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>opentmf-634-v4-client</artifactId>
        <version>${opentmf-634-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>opentmf-637-v4-client</artifactId>
        <version>${opentmf-637-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>opentmf-638-v4-client</artifactId>
        <version>${opentmf-638-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>opentmf-639-v4-client</artifactId>
        <version>${opentmf-639-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>opentmf-641-v4-client</artifactId>
        <version>${opentmf-641-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>opentmf-648-v4-client</artifactId>
        <version>${opentmf-648-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>opentmf-652-v4-client</artifactId>
        <version>${opentmf-652-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>opentmf-663-v4-client</artifactId>
        <version>${opentmf-663-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>opentmf-666-v4-client</artifactId>
        <version>${opentmf-666-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>opentmf-669-v4-client</artifactId>
        <version>${opentmf-669-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>opentmf-681-v4-client</artifactId>
        <version>${opentmf-681-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>org.opentmf.client</groupId>
        <artifactId>opentmf-hub-v4-client</artifactId>
        <version>${opentmf-hub-v4-client.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>${maven-deploy-plugin.version}</version>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <version>${maven-enforcer-plugin.version}</version>
        <executions>
          <execution>
            <id>enforce-maven</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <requireMavenVersion>
                  <version>3.6.3</version>
                </requireMavenVersion>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-gpg-plugin</artifactId>
        <version>${maven-gpg-plugin.version}</version>
        <executions>
          <execution>
            <id>sign-artifacts</id>
            <phase>verify</phase>
            <goals>
              <goal>sign</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-release-plugin</artifactId>
        <version>${maven-release-plugin.version}</version>
        <configuration>
          <useReleaseProfile>false</useReleaseProfile>
          <goals>deploy</goals>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.sonatype.central</groupId>
        <artifactId>central-publishing-maven-plugin</artifactId>
        <version>${central-publishing-maven-plugin.version}</version>
        <extensions>true</extensions>
        <configuration>
          <publishingServerId>publish-to-central</publishingServerId>
          <autoPublish>true</autoPublish>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <scm>
    <url>https://github.com/opentmf/opentmf-versions</url>
    <connection>scm:git:git@github.com:opentmf/opentmf-versions.git</connection>
    <developerConnection>scm:git:git@github.com:opentmf/opentmf-versions.git</developerConnection>
    <tag>HEAD</tag>
  </scm>

</project>
