<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.pia.commons</groupId>
  <artifactId>pia-commons-versions</artifactId>
  <version>1.0.0</version>
  <packaging>pom</packaging>
  <description>
    A Super pom project that exposes the latest release versions of pia-commons artifacts.
  </description>

  <properties>
    <pia-security.version>1.0.1</pia-security.version>
    <pia-commons.version>1.0.0</pia-commons.version>
    <pia-db-lock-service.version>1.0.1</pia-db-lock-service.version>
    <pia-bpmn-sync-service.version>1.0.1</pia-bpmn-sync-service.version>
    <pia-catalog-sync-service.version>1.0.0</pia-catalog-sync-service.version>

    <camunda-incident-logger.version>1.0.0</camunda-incident-logger.version>
    <dynamic-mock-expectations.version>1.0.0</dynamic-mock-expectations.version>
    <camunda-7-test-framework.version>1.0.0</camunda-7-test-framework.version>
    <pia-camunda-7.version>7.21.0.0</pia-camunda-7.version>

    <tmf-v4-models.version>1.0.1</tmf-v4-models.version>
    <tmf-620-model.version>4.1.0.1</tmf-620-model.version>
    <tmf-622-model.version>4.0.0.1</tmf-622-model.version>
    <tmf-629-model.version>4.0.0.1</tmf-629-model.version>
    <tmf-632-model.version>4.0.0.1</tmf-632-model.version>
    <tmf-633-model.version>4.0.0.1</tmf-633-model.version>
    <tmf-634-model.version>4.1.0.1</tmf-634-model.version>
    <tmf-637-model.version>4.0.0.1</tmf-637-model.version>
    <tmf-638-model.version>4.0.0.1</tmf-638-model.version>
    <tmf-639-model.version>4.0.0.1</tmf-639-model.version>
    <tmf-641-model.version>4.1.0.1</tmf-641-model.version>
    <tmf-648-model.version>4.0.0.1</tmf-648-model.version>
    <tmf-651-model.version>4.0.0.1</tmf-651-model.version>
    <tmf-652-model.version>4.0.0.1</tmf-652-model.version>
    <tmf-663-model.version>4.0.0.1</tmf-663-model.version>
    <tmf-666-model.version>4.0.0.1</tmf-666-model.version>
    <tmf-669-model.version>4.0.0.1</tmf-669-model.version>
    <tmf-673-model.version>4.0.1.1</tmf-673-model.version>
    <tmf-674-model.version>4.0.0.1</tmf-674-model.version>
    <tmf-675-model.version>4.0.0.1</tmf-675-model.version>
    <tmf-customer-model.version>4.0.0.1</tmf-customer-model.version>
    <tmf-resource-model.version>4.1.0.1</tmf-resource-model.version>
    <tmf-service-model.version>4.1.0.1</tmf-service-model.version>
    <tmf-product-model.version>4.1.0.1</tmf-product-model.version>
    <tmf-common-model.version>4.1.0.1</tmf-common-model.version>

    <dnext-tmf-v4-models.version>1.0.1</dnext-tmf-v4-models.version>
    <dnext-tmf-620-model.version>4.0.0.1</dnext-tmf-620-model.version>
    <dnext-tmf-622-model.version>4.0.0.1</dnext-tmf-622-model.version>
    <dnext-tmf-638-model.version>4.0.0.1</dnext-tmf-638-model.version>
    <dnext-tmf-641-model.version>4.1.0.1</dnext-tmf-641-model.version>
    <dnext-tmf-663-model.version>4.1.0.1</dnext-tmf-663-model.version>
    <dnext-tmf-666-model.version>4.0.0.1</dnext-tmf-666-model.version>
    <dnext-tmf-common-model.version>4.1.0.1</dnext-tmf-common-model.version>

    <tmf-v4-utils.version>1.0.1</tmf-v4-utils.version>
    <tmf-622-util.version>1.0.1</tmf-622-util.version>
    <tmf-641-util.version>1.0.1</tmf-641-util.version>
    <tmf-common-util.version>1.0.1</tmf-common-util.version>

    <pia-web-clients.version>1.0.2</pia-web-clients.version>
    <pia-webclients-common.version>1.0.2</pia-webclients-common.version>
    <pia-openid-webclient-provider.version>1.0.2</pia-openid-webclient-provider.version>
    <pia-basic-webclient-provider.version>1.0.2</pia-basic-webclient-provider.version>
    <test-all-clients.version>1.0.2</test-all-clients.version>

    <tmf-v4-clients.version>1.0.1</tmf-v4-clients.version>
    <tmf-620-client.version>1.0.1</tmf-620-client.version>
    <tmf-622-client.version>1.0.1</tmf-622-client.version>
    <tmf-629-client.version>1.0.1</tmf-629-client.version>
    <tmf-632-client.version>1.0.1</tmf-632-client.version>
    <tmf-633-client.version>1.0.1</tmf-633-client.version>
    <tmf-634-client.version>1.0.1</tmf-634-client.version>
    <tmf-637-client.version>1.0.1</tmf-637-client.version>
    <tmf-638-client.version>1.0.1</tmf-638-client.version>
    <tmf-639-client.version>1.0.1</tmf-639-client.version>
    <tmf-641-client.version>1.0.1</tmf-641-client.version>
    <tmf-648-client.version>1.0.1</tmf-648-client.version>
    <tmf-652-client.version>1.0.1</tmf-652-client.version>
    <tmf-663-client.version>1.0.1</tmf-663-client.version>
    <tmf-666-client.version>1.0.1</tmf-666-client.version>
    <tmf-669-client.version>1.0.1</tmf-669-client.version>
    <tmf-client-common.version>1.0.1</tmf-client-common.version>

    <!-- Plugins related to release and deployment -->
    <maven-enforcer-plugin.version>3.5.0</maven-enforcer-plugin.version>
    <maven-deploy-plugin.version>3.1.3</maven-deploy-plugin.version>
    <nexus-staging-plugin.version>1.7.0</nexus-staging-plugin.version>

  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>pia-security</artifactId>
        <version>${pia-security.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>pia-commons</artifactId>
        <version>${pia-commons.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>pia-db-lock-service</artifactId>
        <version>${pia-db-lock-service.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>pia-bpmn-sync-service</artifactId>
        <version>${pia-bpmn-sync-service.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>pia-catalog-sync-service</artifactId>
        <version>${pia-catalog-sync-service.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>camunda-incident-logger</artifactId>
        <version>${camunda-incident-logger.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>dynamic-mock-expectations</artifactId>
        <version>${dynamic-mock-expectations.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>camunda-7-test-framework</artifactId>
        <version>${camunda-7-test-framework.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>pia-camunda-7</artifactId>
        <version>${pia-camunda-7.version}</version>
      </dependency>

      <!-- TMF v4 Models -->
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-v4-models</artifactId>
        <version>${tmf-v4-models.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-620-model</artifactId>
        <version>${tmf-620-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-622-model</artifactId>
        <version>${tmf-622-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-629-model</artifactId>
        <version>${tmf-629-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-632-model</artifactId>
        <version>${tmf-632-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-633-model</artifactId>
        <version>${tmf-633-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-634-model</artifactId>
        <version>${tmf-634-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-637-model</artifactId>
        <version>${tmf-637-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-638-model</artifactId>
        <version>${tmf-638-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-639-model</artifactId>
        <version>${tmf-639-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-641-model</artifactId>
        <version>${tmf-641-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-648-model</artifactId>
        <version>${tmf-648-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-651-model</artifactId>
        <version>${tmf-651-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-652-model</artifactId>
        <version>${tmf-652-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-663-model</artifactId>
        <version>${tmf-663-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-666-model</artifactId>
        <version>${tmf-666-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-669-model</artifactId>
        <version>${tmf-669-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-673-model</artifactId>
        <version>${tmf-673-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-674-model</artifactId>
        <version>${tmf-674-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-675-model</artifactId>
        <version>${tmf-675-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-customer-model</artifactId>
        <version>${tmf-customer-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-resource-model</artifactId>
        <version>${tmf-resource-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-service-model</artifactId>
        <version>${tmf-service-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-product-model</artifactId>
        <version>${tmf-product-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-common-model</artifactId>
        <version>${tmf-common-model.version}</version>
      </dependency>

      <!-- DNext TMF v4 Model Extensions -->
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>dnext-tmf-v4-models</artifactId>
        <version>${dnext-tmf-v4-models.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>dnext-tmf-620-model</artifactId>
        <version>${dnext-tmf-620-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>dnext-tmf-622-model</artifactId>
        <version>${dnext-tmf-622-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>dnext-tmf-638-model</artifactId>
        <version>${dnext-tmf-638-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>dnext-tmf-641-model</artifactId>
        <version>${dnext-tmf-641-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>dnext-tmf-663-model</artifactId>
        <version>${dnext-tmf-663-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>dnext-tmf-666-model</artifactId>
        <version>${dnext-tmf-666-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>dnext-tmf-common-model</artifactId>
        <version>${dnext-tmf-common-model.version}</version>
      </dependency>

      <!-- TMF v4 Utils -->
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-v4-utils</artifactId>
        <version>${tmf-v4-utils.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-622-util</artifactId>
        <version>${tmf-622-util.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-641-util</artifactId>
        <version>${tmf-641-util.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-common-util</artifactId>
        <version>${tmf-common-util.version}</version>
      </dependency>

      <!-- PiA Web Clients -->
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>pia-web-clients</artifactId>
        <version>${pia-web-clients.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>pia-webclients-common</artifactId>
        <version>${pia-webclients-common.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>pia-openid-webclient-provider</artifactId>
        <version>${pia-openid-webclient-provider.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>pia-basic-webclient-provider</artifactId>
        <version>${pia-basic-webclient-provider.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>test-all-clients</artifactId>
        <version>${test-all-clients.version}</version>
      </dependency>

      <!-- TMF v4 Clients -->
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-v4-clients</artifactId>
        <version>${tmf-v4-clients.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-620-client</artifactId>
        <version>${tmf-620-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-622-client</artifactId>
        <version>${tmf-622-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-629-client</artifactId>
        <version>${tmf-629-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-632-client</artifactId>
        <version>${tmf-632-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-633-client</artifactId>
        <version>${tmf-633-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-634-client</artifactId>
        <version>${tmf-634-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-637-client</artifactId>
        <version>${tmf-637-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-638-client</artifactId>
        <version>${tmf-638-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-639-client</artifactId>
        <version>${tmf-639-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-641-client</artifactId>
        <version>${tmf-641-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-648-client</artifactId>
        <version>${tmf-648-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-652-client</artifactId>
        <version>${tmf-652-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-663-client</artifactId>
        <version>${tmf-663-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-666-client</artifactId>
        <version>${tmf-666-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-669-client</artifactId>
        <version>${tmf-669-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-client-common</artifactId>
        <version>${tmf-client-common.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <version>${maven-enforcer-plugin.version}</version>
        <executions>
          <execution>
            <id>enforce-maven</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <requireMavenVersion>
                  <version>3.6.3</version>
                </requireMavenVersion>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-deploy-plugin</artifactId>
        <version>${maven-deploy-plugin.version}</version>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.sonatype.plugins</groupId>
        <artifactId>nexus-staging-maven-plugin</artifactId>
        <version>${nexus-staging-plugin.version}</version>
        <executions>
          <execution>
            <id>default-deploy</id>
            <phase>deploy</phase>
            <goals>
              <goal>deploy</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <serverId>pia-commons-release</serverId>
          <nexusUrl>https://nexus.dnext-pia.com/</nexusUrl>
          <skipStaging>true</skipStaging>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <distributionManagement>
    <repository>
      <id>pia-commons-release</id>
      <url>https://nexus.dnext-pia.com/repository/pia-commons-release/</url>
    </repository>
    <snapshotRepository>
      <id>pia-commons-snapshot</id>
      <url>https://nexus.dnext-pia.com/repository/pia-commons-snapshot/</url>
    </snapshotRepository>
  </distributionManagement>

  <scm>
    <connection>scm:git:git@github.com:pia-commons/pia-commons-versions.git</connection>
    <developerConnection>scm:git:git@github.com:pia-commons/pia-commons-versions.git</developerConnection>
    <tag>pia-commons-versions-1.0.0</tag>
  </scm>

</project>
