<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.pia.commons</groupId>
  <artifactId>pia-commons-versions</artifactId>
  <version>1.1.9-SNAPSHOT</version>
  <packaging>pom</packaging>
  <description>
    A Super pom project that exposes the latest release versions of pia-commons artifacts.
  </description>

  <properties>
    <pia-security.version>1.0.9</pia-security.version>
    <pia-commons.version>1.0.2</pia-commons.version>
    <pia-db-lock-service.version>1.0.7</pia-db-lock-service.version>
    <pia-bpmn-sync-service.version>1.1.0</pia-bpmn-sync-service.version>
    <pia-catalog-sync-service.version>1.0.8</pia-catalog-sync-service.version>
    <auditor-aware-jpa.version>1.0.2</auditor-aware-jpa.version>

    <camunda-incident-logger.version>1.0.2</camunda-incident-logger.version>
    <dynamic-mock-expectations.version>1.0.1</dynamic-mock-expectations.version>
    <camunda-7-test-framework.version>1.0.2</camunda-7-test-framework.version>
    <pia-camunda-7.version>22.0.6</pia-camunda-7.version>

    <tmf-v4-models.version>1.0.3</tmf-v4-models.version>
    <tmf-620-v4-model.version>4.1.0.3</tmf-620-v4-model.version>
    <tmf-622-v4-model.version>4.0.0.3</tmf-622-v4-model.version>
    <tmf-629-v4-model.version>4.0.0.3</tmf-629-v4-model.version>
    <tmf-632-v4-model.version>4.0.0.3</tmf-632-v4-model.version>
    <tmf-633-v4-model.version>4.0.0.3</tmf-633-v4-model.version>
    <tmf-634-v4-model.version>4.1.0.3</tmf-634-v4-model.version>
    <tmf-637-v4-model.version>4.0.0.3</tmf-637-v4-model.version>
    <tmf-638-v4-model.version>4.0.0.3</tmf-638-v4-model.version>
    <tmf-639-v4-model.version>4.0.0.3</tmf-639-v4-model.version>
    <tmf-641-v4-model.version>4.1.0.3</tmf-641-v4-model.version>
    <tmf-648-v4-model.version>4.0.0.3</tmf-648-v4-model.version>
    <tmf-651-v4-model.version>4.0.0.3</tmf-651-v4-model.version>
    <tmf-652-v4-model.version>4.0.0.3</tmf-652-v4-model.version>
    <tmf-663-v4-model.version>4.0.0.3</tmf-663-v4-model.version>
    <tmf-666-v4-model.version>4.0.0.3</tmf-666-v4-model.version>
    <tmf-669-v4-model.version>4.0.0.3</tmf-669-v4-model.version>
    <tmf-673-v4-model.version>4.0.1.3</tmf-673-v4-model.version>
    <tmf-674-v4-model.version>4.0.0.3</tmf-674-v4-model.version>
    <tmf-675-v4-model.version>4.0.0.3</tmf-675-v4-model.version>
    <tmf-681-v4-model.version>4.0.0.3</tmf-681-v4-model.version>
    <tmf-customer-v4-model.version>4.0.0.3</tmf-customer-v4-model.version>
    <tmf-resource-v4-model.version>4.1.0.3</tmf-resource-v4-model.version>
    <tmf-service-v4-model.version>4.1.0.3</tmf-service-v4-model.version>
    <tmf-product-v4-model.version>4.1.0.3</tmf-product-v4-model.version>
    <tmf-common-v4-model.version>4.1.0.3</tmf-common-v4-model.version>

    <dnext-tmf-v4-models.version>1.0.6</dnext-tmf-v4-models.version>
    <dnext-tmf-620-v4-model.version>4.0.0.6</dnext-tmf-620-v4-model.version>
    <dnext-tmf-622-v4-model.version>4.0.0.6</dnext-tmf-622-v4-model.version>
    <dnext-tmf-633-v4-model.version>4.0.0.6</dnext-tmf-633-v4-model.version>
    <dnext-tmf-638-v4-model.version>4.0.0.6</dnext-tmf-638-v4-model.version>
    <dnext-tmf-641-v4-model.version>4.1.0.6</dnext-tmf-641-v4-model.version>
    <dnext-tmf-663-v4-model.version>4.1.0.6</dnext-tmf-663-v4-model.version>
    <dnext-tmf-666-v4-model.version>4.0.0.6</dnext-tmf-666-v4-model.version>
    <dnext-tmf-common-v4-model.version>4.1.0.6</dnext-tmf-common-v4-model.version>

    <tmf-v4-utils.version>1.0.3</tmf-v4-utils.version>
    <tmf-622-v4-util.version>1.0.3</tmf-622-v4-util.version>
    <tmf-641-v4-util.version>1.0.3</tmf-641-v4-util.version>
    <tmf-common-v4-util.version>1.0.3</tmf-common-v4-util.version>

    <pia-web-clients.version>1.0.8</pia-web-clients.version>
    <pia-webclients-common.version>1.0.8</pia-webclients-common.version>
    <pia-openid-webclient-provider.version>1.0.8</pia-openid-webclient-provider.version>
    <pia-openid-webclients-starter.version>1.0.8</pia-openid-webclients-starter.version>
    <pia-basic-webclient-provider.version>1.0.8</pia-basic-webclient-provider.version>
    <pia-basic-webclients-starter.version>1.0.8</pia-basic-webclients-starter.version>
    <test-all-clients.version>1.0.8</test-all-clients.version>

    <tmf-clients-base.version>1.0.4</tmf-clients-base.version>

    <tmf-v4-clients.version>1.0.9</tmf-v4-clients.version>
    <tmf-620-v4-client.version>1.0.9</tmf-620-v4-client.version>
    <tmf-622-v4-client.version>1.0.9</tmf-622-v4-client.version>
    <tmf-629-v4-client.version>1.0.9</tmf-629-v4-client.version>
    <tmf-632-v4-client.version>1.0.9</tmf-632-v4-client.version>
    <tmf-633-v4-client.version>1.0.9</tmf-633-v4-client.version>
    <tmf-634-v4-client.version>1.0.9</tmf-634-v4-client.version>
    <tmf-637-v4-client.version>1.0.9</tmf-637-v4-client.version>
    <tmf-638-v4-client.version>1.0.9</tmf-638-v4-client.version>
    <tmf-639-v4-client.version>1.0.9</tmf-639-v4-client.version>
    <tmf-641-v4-client.version>1.0.9</tmf-641-v4-client.version>
    <tmf-648-v4-client.version>1.0.9</tmf-648-v4-client.version>
    <tmf-652-v4-client.version>1.0.9</tmf-652-v4-client.version>
    <tmf-663-v4-client.version>1.0.9</tmf-663-v4-client.version>
    <tmf-666-v4-client.version>1.0.9</tmf-666-v4-client.version>
    <tmf-669-v4-client.version>1.0.9</tmf-669-v4-client.version>
    <tmf-681-v4-client.version>1.0.9</tmf-681-v4-client.version>
    <tmf-hub-v4-client.version>1.0.9</tmf-hub-v4-client.version>

    <!-- Plugins related to release and deployment -->
    <maven-enforcer-plugin.version>3.5.0</maven-enforcer-plugin.version>
    <maven-deploy-plugin.version>3.1.3</maven-deploy-plugin.version>
    <nexus-staging-plugin.version>1.7.0</nexus-staging-plugin.version>

  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>pia-security</artifactId>
        <version>${pia-security.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>pia-commons</artifactId>
        <version>${pia-commons.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>pia-db-lock-service</artifactId>
        <version>${pia-db-lock-service.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>pia-bpmn-sync-service</artifactId>
        <version>${pia-bpmn-sync-service.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>pia-catalog-sync-service</artifactId>
        <version>${pia-catalog-sync-service.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>auditor-aware-jpa</artifactId>
        <version>${auditor-aware-jpa.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>camunda-incident-logger</artifactId>
        <version>${camunda-incident-logger.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>dynamic-mock-expectations</artifactId>
        <version>${dynamic-mock-expectations.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>camunda-7-test-framework</artifactId>
        <version>${camunda-7-test-framework.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>pia-camunda-7</artifactId>
        <version>${pia-camunda-7.version}</version>
      </dependency>

      <!-- TMF v4 Models -->
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-v4-models</artifactId>
        <version>${tmf-v4-models.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-620-v4-model</artifactId>
        <version>${tmf-620-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-622-v4-model</artifactId>
        <version>${tmf-622-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-629-v4-model</artifactId>
        <version>${tmf-629-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-632-v4-model</artifactId>
        <version>${tmf-632-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-633-v4-model</artifactId>
        <version>${tmf-633-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-634-v4-model</artifactId>
        <version>${tmf-634-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-637-v4-model</artifactId>
        <version>${tmf-637-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-638-v4-model</artifactId>
        <version>${tmf-638-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-639-v4-model</artifactId>
        <version>${tmf-639-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-641-v4-model</artifactId>
        <version>${tmf-641-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-648-v4-model</artifactId>
        <version>${tmf-648-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-651-v4-model</artifactId>
        <version>${tmf-651-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-652-v4-model</artifactId>
        <version>${tmf-652-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-663-v4-model</artifactId>
        <version>${tmf-663-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-666-v4-model</artifactId>
        <version>${tmf-666-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-669-v4-model</artifactId>
        <version>${tmf-669-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-673-v4-model</artifactId>
        <version>${tmf-673-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-674-v4-model</artifactId>
        <version>${tmf-674-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-675-v4-model</artifactId>
        <version>${tmf-675-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-681-v4-model</artifactId>
        <version>${tmf-681-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-customer-v4-model</artifactId>
        <version>${tmf-customer-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-resource-v4-model</artifactId>
        <version>${tmf-resource-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-service-v4-model</artifactId>
        <version>${tmf-service-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-product-v4-model</artifactId>
        <version>${tmf-product-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-common-v4-model</artifactId>
        <version>${tmf-common-v4-model.version}</version>
      </dependency>

      <!-- DNext TMF v4 Model Extensions -->
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>dnext-tmf-v4-models</artifactId>
        <version>${dnext-tmf-v4-models.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>dnext-tmf-620-v4-model</artifactId>
        <version>${dnext-tmf-620-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>dnext-tmf-622-v4-model</artifactId>
        <version>${dnext-tmf-622-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>dnext-tmf-633-v4-model</artifactId>
        <version>${dnext-tmf-633-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>dnext-tmf-638-v4-model</artifactId>
        <version>${dnext-tmf-638-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>dnext-tmf-641-v4-model</artifactId>
        <version>${dnext-tmf-641-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>dnext-tmf-663-v4-model</artifactId>
        <version>${dnext-tmf-663-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>dnext-tmf-666-v4-model</artifactId>
        <version>${dnext-tmf-666-v4-model.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>dnext-tmf-common-v4-model</artifactId>
        <version>${dnext-tmf-common-v4-model.version}</version>
      </dependency>

      <!-- TMF v4 Utils -->
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-v4-utils</artifactId>
        <version>${tmf-v4-utils.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-622-v4-util</artifactId>
        <version>${tmf-622-v4-util.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-641-v4-util</artifactId>
        <version>${tmf-641-v4-util.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-common-v4-util</artifactId>
        <version>${tmf-common-v4-util.version}</version>
      </dependency>

      <!-- PiA Web Clients -->
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>pia-web-clients</artifactId>
        <version>${pia-web-clients.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>pia-webclients-common</artifactId>
        <version>${pia-webclients-common.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>pia-openid-webclient-provider</artifactId>
        <version>${pia-openid-webclient-provider.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>pia-openid-webclients-starter</artifactId>
        <version>${pia-openid-webclients-starter.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>pia-basic-webclient-provider</artifactId>
        <version>${pia-basic-webclient-provider.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>pia-basic-webclients-starter</artifactId>
        <version>${pia-basic-webclients-starter.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>test-all-clients</artifactId>
        <version>${test-all-clients.version}</version>
      </dependency>

      <!-- TMF Clients Base -->
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-clients-base</artifactId>
        <version>${tmf-clients-base.version}</version>
      </dependency>

      <!-- TMF v4 Clients -->
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-v4-clients</artifactId>
        <version>${tmf-v4-clients.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-620-v4-client</artifactId>
        <version>${tmf-620-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-622-v4-client</artifactId>
        <version>${tmf-622-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-629-v4-client</artifactId>
        <version>${tmf-629-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-632-v4-client</artifactId>
        <version>${tmf-632-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-633-v4-client</artifactId>
        <version>${tmf-633-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-634-v4-client</artifactId>
        <version>${tmf-634-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-637-v4-client</artifactId>
        <version>${tmf-637-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-638-v4-client</artifactId>
        <version>${tmf-638-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-639-v4-client</artifactId>
        <version>${tmf-639-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-641-v4-client</artifactId>
        <version>${tmf-641-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-648-v4-client</artifactId>
        <version>${tmf-648-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-652-v4-client</artifactId>
        <version>${tmf-652-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-663-v4-client</artifactId>
        <version>${tmf-663-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-666-v4-client</artifactId>
        <version>${tmf-666-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-669-v4-client</artifactId>
        <version>${tmf-669-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-681-v4-client</artifactId>
        <version>${tmf-681-v4-client.version}</version>
      </dependency>
      <dependency>
        <groupId>com.pia.commons</groupId>
        <artifactId>tmf-hub-v4-client</artifactId>
        <version>${tmf-hub-v4-client.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <version>${maven-enforcer-plugin.version}</version>
        <executions>
          <execution>
            <id>enforce-maven</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <requireMavenVersion>
                  <version>3.6.3</version>
                </requireMavenVersion>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-deploy-plugin</artifactId>
        <version>${maven-deploy-plugin.version}</version>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.sonatype.plugins</groupId>
        <artifactId>nexus-staging-maven-plugin</artifactId>
        <version>${nexus-staging-plugin.version}</version>
        <executions>
          <execution>
            <id>default-deploy</id>
            <phase>deploy</phase>
            <goals>
              <goal>deploy</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <serverId>pia-commons-release</serverId>
          <nexusUrl>https://nexus.dnext-pia.com/</nexusUrl>
          <skipStaging>true</skipStaging>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <distributionManagement>
    <repository>
      <id>pia-commons-release</id>
      <url>https://nexus.dnext-pia.com/repository/pia-commons-release/</url>
    </repository>
    <snapshotRepository>
      <id>pia-commons-snapshot</id>
      <url>https://nexus.dnext-pia.com/repository/pia-commons-snapshot/</url>
    </snapshotRepository>
  </distributionManagement>

  <scm>
    <connection>scm:git:git@github.com:pia-commons/pia-commons-versions.git</connection>
    <developerConnection>scm:git:git@github.com:pia-commons/pia-commons-versions.git</developerConnection>
    <tag>HEAD</tag>
  </scm>

</project>
